// lib/emoji_map.dart

const Map<String, List<Map<String, String>>> fullEmojiData = {
  'Smileys & Emotion': [
    {'char': '😀', 'name': 'grinning face happy smile'},
    {'char': '😃', 'name': 'grinning face big eyes open mouth'},
    {'char': '😄', 'name': 'grinning face smiling eyes happy'},
    {'char': '😁', 'name': 'beaming face grinning proud'},
    {'char': '😆', 'name': 'grinning squinting face laughing'},
    {'char': '😅', 'name': 'grinning face sweat relief awkward'},
    {'char': '😂', 'name': 'face with tears of joy laughing crying lol'},
    {'char': '🤣', 'name': 'rofl rolling on the floor laughing'},
    {'char': '😊', 'name': 'smiling face smiling eyes blush warm'},
    {'char': '😇', 'name': 'smiling face with halo angel innocent'},
    {'char': '🙂', 'name': 'slightly smiling face passive'},
    {'char': '🙃', 'name': 'upside-down face silly sarcasm'},
    {'char': '😉', 'name': 'winking face wink subtle'},
    {'char': '😌', 'name': 'relieved face calm peace'},
    {'char': '😍', 'name': 'smiling face with heart eyes love adore'},
    {'char': '🥰', 'name': 'smiling face with hearts affectionate'},
    {'char': '😘', 'name': 'face blowing a kiss love romantic'},
    {'char': '😋', 'name': 'face savoring food delicious tasty tongue'},
    {'char': '😛', 'name': 'face with tongue out playful'},
    {'char': '😜', 'name': 'winking face with tongue crazy silly'},
    {'char': '🤪', 'name': 'zany face wild goofy'},
    {'char': '🤨', 'name': 'face with raised eyebrow suspicious skeptical'},
    {'char': '🧐', 'name': 'face with monocle sophisticated curious'},
    {'char': '🤓', 'name': 'nerd face geek smart tech'},
    {'char': '😎', 'name': 'smiling face with sunglasses cool rad'},
    {'char': '🥳', 'name': 'partying face celebrate horn'},
    {'char': '😏', 'name': 'smirking face sly smug'},
    {'char': '😒', 'name': 'unamused face annoyed bored'},
    {'char': '😞', 'name': 'disappointed face sad regret'},
    {'char': '😔', 'name': 'pensive face deep thought melancholy'},
    {'char': '😟', 'name': 'worried face anxious concerned'},
    {'char': '😕', 'name': 'confused face puzzled'},
    {'char': '🙁', 'name': 'slightly frowning face sad'},
    {'char': '☹️', 'name': 'frowning face unhappy'},
    {'char': '😣', 'name': 'persevering face struggling'},
    {'char': '😖', 'name': 'confounded face distressed'},
    {'char': '😫', 'name': 'tired face exhausted weary'},
    {'char': '😩', 'name': 'weary face fed up'},
    {'char': '🥺', 'name': 'pleading face puppy eyes begging'},
    {'char': '😢', 'name': 'crying face tear sad'},
    {'char': '😭', 'name': 'loudly crying face sobbing devastated'},
    {'char': '😤', 'name': 'face with steam from nose angry proud triumph'},
    {'char': '😠', 'name': 'angry face mad frustrated'},
    {'char': '😡', 'name': 'pouting face furious raging red'},
    {'char': '🤬', 'name': 'face with symbols on mouth cursing angry'},
    {'char': '🤯', 'name': 'exploding head mind blown shock amaze'},
    {'char': '😳', 'name': 'flushed face embarrassed shocked wide eyes'},
    {'char': '🥵', 'name': 'hot face sweating red fever overheated'},
    {'char': '🥶', 'name': 'cold face freezing blue ice winter'},
    {'char': '😱', 'name': 'face screaming in fear scared terrified shock'},
    {'char': '😨', 'name': 'fearful face scared worried'},
    {'char': '😰', 'name': 'anxious face with sweat cold sweat'},
    {'char': '😥', 'name': 'sad but relieved face disappointment'},
    {'char': '😓', 'name': 'downcast face with sweat stressed anxiety'},
    {'char': '🤗', 'name': 'hugging face open hands warmth'},
    {'char': '🤔', 'name': 'thinking face pondering wondering question'},
    {'char': '🤭', 'name': 'face with hand over mouth giggling oops secret'},
    {'char': '🤫', 'name': 'shushing face quiet silence'},
    {'char': '🤥', 'name': 'lying face long nose pinocchio'},
    {'char': '😶', 'name': 'face without mouth silent blank'},
    {'char': '😐', 'name': 'neutral face poker face deadpan'},
    {'char': '😑', 'name': 'expressionless face unamused'},
    {'char': '😬', 'name': 'grimacing face awkward cringe cringe-worthy'},
    {'char': '🙄', 'name': 'face with rolling eyes eyeroll annoyed'},
    {'char': '😯', 'name': 'hushed face surprised open mouth'},
    {'char': '😦', 'name': 'frowning face with open mouth shock'},
    {'char': '😧', 'name': 'anguished face pained distressed'},
    {'char': '😮', 'name': 'face with open mouth surprise'},
    {'char': '😲', 'name': 'astonished face amazed shock'},
    {'char': '🥱', 'name': 'yawning face tired sleep bored'},
    {'char': '😴', 'name': 'sleeping face snoring zzz'},
    {'char': '🤤', 'name': 'drooling face desire asleep'},
    {'char': '😪', 'name': 'sleepy face tired bubble sleep'},
    {'char': '😵', 'name': 'dizzy face knocked out stunned'},
    {'char': '🤐', 'name': 'zipper-mouth face sealed secret quiet'},
    {'char': '🥴', 'name': 'woozy face drunk dazed lightheaded'},
    {'char': '🤢', 'name': 'nauseated face sick gross disgusted green'},
    {'char': '🤮', 'name': 'face vomiting throwing up spewing puke'},
    {'char': '🤧', 'name': 'sneezing face cold flu tissue allergy'},
    {'char': '😷', 'name': 'face with medical mask doctor sick protection'},
    {'char': '🤒', 'name': 'face with thermometer sick fever illness'},
    {'char': '🤕', 'name': 'face with head-bandage hurt injured head wound'},
    {'char': '🤑', 'name': 'money-mouth face rich cash greed dollar'},
    {'char': '🤠', 'name': 'cowboy hat face hat country wild west'},
    {'char': '🤩', 'name': 'star struck face amazed excited'},
    {'char': '🥲', 'name': 'smiling face with tear emotional'},
    {'char': '😮‍💨', 'name': 'face exhaling relief tired'},
    {'char': '😵‍💫', 'name': 'face with spiral eyes dizzy confused'},
    {'char': '🫠', 'name': 'melting face embarrassed overwhelmed'},
    {'char': '🫡', 'name': 'saluting face respect honor'},
    {'char': '🫢', 'name': 'face with open eyes surprise shock'},
    {'char': '🫣', 'name': 'face peeking eyes shy scared'},
    {'char': '🫥', 'name': 'dotted line face invisible hidden'},
    {'char': '🫤', 'name': 'face diagonal mouth unsure'},
    {'char': '🥸', 'name': 'disguised face glasses mustache spy'},
    {'char': '🥱', 'name': 'yawn face sleep exhaustion morning early'},
    {'char': '🥺', 'name': 'please begging sad target tearful look eyes'},
    {'char': '😼', 'name': 'cat smirk feline smile funny dynamic alignment'},
    {'char': '🤠', 'name': 'cowboy country ranger western farm hat layout'},
    {'char': '🤷‍♂️', 'name': 'shrug face indifferent doubt uncertainty'},
    {'char': '😈', 'name': 'smiling face with horns devil evil mischievous purple'},
    {'char': '👿', 'name': 'angry face with horns demon devil mad purple'},
    {'char': '👹', 'name': 'ogre japanese folklore monster scary red'},
    {'char': '👺', 'name': 'goblin mask long nose monster japanese'},
    {'char': '🤡', 'name': 'clown face circus funny creepy'},
    {'char': '💩', 'name': 'pile of poo poop turd smile'},
    {'char': '👻', 'name': 'ghost spooky halloween phantom white'},
    {'char': '💀', 'name': 'skull dead bone skeleton death goth'},
    {'char': '☠️', 'name': 'skull and crossbones pirate danger toxic poison'},
    {'char': '👽', 'name': 'alien space extraterrestrial sci-fi ufo mars'},
    {'char': '👾', 'name': 'alien monster retro video game pixel arcade'},
    {'char': '🤖', 'name': 'robot face machine bot tech cyborg'},
    {'char': '🎃', 'name': 'jack-o-lantern pumpkin halloween scary orange'},
    {'char': '😺', 'name': 'grinning cat face smile'},
    {'char': '😸', 'name': 'grinning cat face smiling eyes'},
    {'char': '😹', 'name': 'cat face with tears of joy laughing crying lol'},
    {'char': '😻', 'name': 'smiling cat face with heart-eyes love adore'},
    {'char': '😼', 'name': 'cat face with wry smile smirk cynical'},
    {'char': '😽', 'name': 'kissing cat face love sweet'},
    {'char': '🙀', 'name': 'weary cat face shocked surprised terrified'},
    {'char': '😿', 'name': 'crying cat face sad tear'},
    {'char': '😾', 'name': 'pouting cat face angry mad grumpy'},
  ],
  'Hand gestures' : [

    {'char': '👋', 'name': 'waving hand hello goodbye hi wave'},
    {'char': '🤚', 'name': 'raised back of hand stop high five'},
    {'char': '🖐️', 'name': 'hand with fingers splayed open palm'},
    {'char': '✋', 'name': 'raised hand stop halt'},
    {'char': '🖖', 'name': 'vulcan salute spock live long and prosper sci-fi'},
    {'char': '👌', 'name': 'ok hand sign gesture correct fine good'},
    {'char': '🤏', 'name': 'pinching hand small little tiny fraction'},
    {'char': '✌️', 'name': 'victory hand peace sign two double'},
    {'char': '🤞', 'name': 'fingers crossed luck hope promise'},
    {'char': '🤟', 'name': 'love-you gesture sign rock on'},
    {'char': '🤘', 'name': 'sign of the horns rock on heavy metal'},
    {'char': '🤙', 'name': 'call me hand phone sign gesture'},
    {'char': '👈', 'name': 'backhand index pointing left direction'},
    {'char': '👉', 'name': 'backhand index pointing right direction'},
    {'char': '👆', 'name': 'backhand index pointing up direction up'},
    {'char': '🖕', 'name': 'middle finger flip off rude gesture insulting'},
    {'char': '👇', 'name': 'backhand index pointing down direction down'},
    {'char': '☝️', 'name': 'index pointing up gesture number one attention'},
    {'char': '👍', 'name': 'thumbs up ok good yes agree approve like'},
    {'char': '👎', 'name': 'thumbs down bad no disagree disapprove dislike'},
    {'char': '✊', 'name': 'raised fist power fight solidarity'},
    {'char': '👊', 'name': 'oncoming fist punch hit bump brofist'},
    {'char': '🤛', 'name': 'left-facing fist punch hit'},
    {'char': '🤜', 'name': 'right-facing fist punch hit'},
    {'char': '👏', 'name': 'clapping hands applause bravo praise good job'},
    {'char': '🙌', 'name': 'raised hands celebrate banzai hallelujah'},
    {'char': '👐', 'name': 'open hands hug welcome honesty'},
    {'char': '🤲', 'name': 'palms up together prayer open petition'},
    {'char': '🤝', 'name': 'handshake agreement deal shaking hands business'},
    {'char': '🙏', 'name': 'folded hands pray please thank you namaste high five'},
    {'char': '✍️', 'name': 'writing hand pen pencil draw write'},
    {'char': '💅', 'name': 'nail polish manicure beauty cosmetic fashion'},
    {'char': '🤳', 'name': 'selfie phone camera taking picture'},
    {'char': '💪', 'name': 'flexed biceps muscle strong power fitness gym working out'},
  ],
  'Emotion & slang' : [
    {'char': '🧠', 'name': 'brain mind intelligence smart thinker anatomy'},
    {'char': '👀', 'name': 'eyes look watch see suspicious sneaky'},
    {'char': '👅', 'name': 'tongue taste lick mouthful speech'},
    {'char': '❤️', 'name': 'red heart love passion romance'},
    {'char': '🧡', 'name': 'orange heart love care comfort'},
    {'char': '💛', 'name': 'yellow heart friendship warmth light'},
    {'char': '💚', 'name': 'green heart nature environment jealousy'},
    {'char': '💙', 'name': 'blue heart trust loyalty peace'},
    {'char': '💜', 'name': 'purple heart royalty wealth compassion'},
    {'char': '🖤', 'name': 'black heart dark goth sorrow mourning'},
    {'char': '🤍', 'name': 'white heart pure clean light'},
    {'char': '🤎', 'name': 'brown heart solid earth wood'},
    {'char': '💔', 'name': 'broken heart heartbreak sad separation split'},
    {'char': '🔥', 'name': 'fire hot burn flame lit epic popular trending'},
    {'char': '💥', 'name': 'collision explosion burst bang dynamic spark'},
    {'char': '✨', 'name': 'sparkles glitter shiny clean magic stars new'},
    {'char': '🌟', 'name': 'glowing star sparkle bright stellar award'},
    {'char': '💯', 'name': 'hundred points perfect standard score full marks keeping it real'},
  ],
  'Animals, Nature & Weather': [
    {'char': '🐶', 'name': 'dog face puppy pet animal loyal cute'},
    {'char': '🐱', 'name': 'cat face kitten pet animal cute furry'},
    {'char': '🐭', 'name': 'mouse face rodent animal tiny cute'},
    {'char': '🐹', 'name': 'hamster face pet animal small cute'},
    {'char': '🐰', 'name': 'rabbit bunny face animal spring cute'},
    {'char': '🦊', 'name': 'fox face animal clever wild orange'},
    {'char': '🐻', 'name': 'bear face animal forest wild cute'},
    {'char': '🐼', 'name': 'panda face animal bamboo china cute'},
    {'char': '🐨', 'name': 'koala face animal australia eucalyptus cute'},
    {'char': '🐯', 'name': 'tiger face animal wild stripes jungle'},
    {'char': '🦁', 'name': 'lion face king animal jungle brave'},
    {'char': '🐮', 'name': 'cow face farm animal milk'},
    {'char': '🐷', 'name': 'pig face farm animal cute'},
    {'char': '🐸', 'name': 'frog face animal green nature'},
    {'char': '🐵', 'name': 'monkey face animal jungle funny'},
    {'char': '🐔', 'name': 'chicken face bird farm animal'},
    {'char': '🐧', 'name': 'penguin bird animal ice cold'},
    {'char': '🐦', 'name': 'bird animal flying nature'},
    {'char': '🐤', 'name': 'baby chick bird cute yellow'},
    {'char': '🦄', 'name': 'unicorn fantasy magical horse rainbow'},
    {'char': '🐝', 'name': 'bee insect honey nature work'},
    {'char': '🦋', 'name': 'butterfly insect beauty transformation nature'},
    {'char': '🐌', 'name': 'snail slow animal shell'},
    {'char': '🐞', 'name': 'ladybug insect lucky nature'},
    {'char': '🐢', 'name': 'turtle animal slow shell ocean'},
    {'char': '🐍', 'name': 'snake reptile animal danger'},
    {'char': '🦖', 'name': 't rex dinosaur prehistoric monster'},
    {'char': '🐳', 'name': 'whale ocean animal sea giant'},
    {'char': '🐬', 'name': 'dolphin ocean animal smart sea'},
    {'char': '🐟', 'name': 'fish ocean animal swimming'},
    {'char': '🐙', 'name': 'octopus sea animal tentacles ocean'},
    {'char': '🌸', 'name': 'flower blossom spring beauty nature'},
    {'char': '🌹', 'name': 'rose flower love romance beauty'},
    {'char': '🌺', 'name': 'hibiscus flower tropical nature'},
    {'char': '🌻', 'name': 'sunflower flower happy bright summer'},
    {'char': '🌱', 'name': 'seedling plant growth nature environment'},
    {'char': '🌲', 'name': 'evergreen tree forest nature'},
    {'char': '🌴', 'name': 'palm tree tropical beach summer'},
    {'char': '🌵', 'name': 'cactus desert plant dry nature'},
    {'char': '🍀', 'name': 'four leaf clover luck green'},
    {'char': '🍁', 'name': 'maple leaf autumn fall nature'},
    {'char': '🍂', 'name': 'fallen leaves autumn season'},
    {'char': '🌈', 'name': 'rainbow colors hope nature'},
    {'char': '☀️', 'name': 'sun bright weather day light'},
    {'char': '🌤️', 'name': 'sun behind cloud partly cloudy weather'},
    {'char': '☁️', 'name': 'cloud sky weather cloudy'},
    {'char': '🌧️', 'name': 'rain cloud weather storm'},
    {'char': '⛈️', 'name': 'thunderstorm lightning rain weather'},
    {'char': '❄️', 'name': 'snowflake winter cold ice'},
    {'char': '🌊', 'name': 'wave ocean water sea tsunami'},
    // Additions (No Repetitions)
    {'char': '🐺', 'name': 'wolf face animal wild predator lone pack'},
    {'char': '🐗', 'name': 'boar wild pig tusk animal forest'},
    {'char': '🐴', 'name': 'horse face animal domestic riding race'},
    {'char': '🐏', 'name': 'ram male sheep horns domestic farm'},
    {'char': '🐐', 'name': 'goat farm animal horned domestic goat'},
    {'char': '🦌', 'name': 'deer animal forest wild stag antlers'},
    {'char': '🦍', 'name': 'gorilla ape jungle animal strong'},
    {'char': '🐒', 'name': 'monkey primate jungle wild tails'},
    {'char': '🦅', 'name': 'eagle bird prey predator majestic usa freedom'},
    {'char': '🦉', 'name': 'owl bird night wise predator nocturnal'},
    {'char': '🦈', 'name': 'shark predator ocean fish dangerous water'},
    {'char': '🕷️', 'name': 'spider insect arachnid web creepy halloween'},
    {'char': '🦂', 'name': 'scorpion insect desert venom stinger'},
    {'char': '🌲', 'name': 'pine tree forest needle wood nature'},
    {'char': '🌱', 'name': 'sprout herb agriculture plant farming'},
    {'char': '🌿', 'name': 'herb leaf greenery seasoning medical nature'},
    {'char': '🍄', 'name': 'mushroom fungus toadstool forest nature cooking'},
    {'char': '⭐', 'name': 'star space sky sparkling gold yellow'},
    {'char': '🔮', 'name': 'mystic fortune teller glass sphere magic'},
    {'char': '💨', 'name': 'dash wind running puff steam fast smoke'},
  ],
  'Food & Drink': [
    {'char': '🍎', 'name': 'red apple fruit healthy food'},
    {'char': '🍌', 'name': 'banana fruit yellow food'},
    {'char': '🍇', 'name': 'grapes fruit sweet food'},
    {'char': '🍉', 'name': 'watermelon fruit summer fresh'},
    {'char': '🍓', 'name': 'strawberry fruit sweet love'},
    {'char': '🍒', 'name': 'cherries fruit sweet red'},
    {'char': '🍑', 'name': 'peach fruit juicy'},
    {'char': '🥭', 'name': 'mango fruit tropical sweet'},
    {'char': '🍍', 'name': 'pineapple fruit tropical'},
    {'char': '🥥', 'name': 'coconut fruit tropical drink'},
    {'char': '🍔', 'name': 'hamburger fast food burger'},
    {'char': '🍟', 'name': 'fries french fries fast food'},
    {'char': '🍕', 'name': 'pizza italian food cheese'},
    {'char': '🌭', 'name': 'hot dog food sausage'},
    {'char': '🌮', 'name': 'taco mexican food'},
    {'char': '🍜', 'name': 'noodles ramen soup asian food'},
    {'char': '🍣', 'name': 'sushi japanese food fish rice'},
    {'char': '🍚', 'name': 'rice food meal'},
    {'char': '🍞', 'name': 'bread bakery food'},
    {'char': '🧀', 'name': 'cheese dairy food'},
    {'char': '🍰', 'name': 'cake dessert birthday sweet'},
    {'char': '🍪', 'name': 'cookie biscuit dessert sweet'},
    {'char': '🍫', 'name': 'chocolate candy sweet'},
    {'char': '🍿', 'name': 'popcorn movie snack'},
    {'char': '🍺', 'name': 'beer drink party'},
    {'char': '🍷', 'name': 'wine drink glass'},
    {'char': '🥤', 'name': 'cup drink soda beverage'},
    {'char': '🧃', 'name': 'juice box drink'},
    // Additions (No Repetitions)
    {'char': '🍏', 'name': 'green apple fruit sour crisp food'},
    {'char': '🍊', 'name': 'tangerine orange citrus fruit sweet food'},
    {'char': '🍋', 'name': 'lemon fruit sour yellow citrus food'},
    {'char': '🥝', 'name': 'kiwi fruit fuzzy green tropical food'},
    {'char': '🥑', 'name': 'avocado vegetable fruit healthy fat guacamole food'},
    {'char': '🥦', 'name': 'broccoli vegetable green tree healthy food'},
    {'char': '🥩', 'name': 'meat cut steak beef pork raw cooking food'},
    {'char': '🥓', 'name': 'bacon pork meat breakfast crispy salty food'},
    {'char': '🍳', 'name': 'egg cooking frying pan breakfast food'},
    {'char': '🥞', 'name': 'pancakes hotcakes breakfast sweet syrup food'},
    {'char': '🌯', 'name': 'burrito mexican food wrap wrap meat beans cheese'},
    {'char': '🥘', 'name': 'shallow pan food paella stew skillet dinner'},
    {'char': '🍲', 'name': 'pot of food stew soup hot meal comfort'},
    {'char': '🥣', 'name': 'bowl with spoon cereal soup oatmeal breakfast'},
    {'char': '🍦', 'name': 'soft ice cream dairy dessert sweet cone summer'},
    {'char': '🍧', 'name': 'shaved ice dessert sweet summer syrup ice'},
    {'char': '🍩', 'name': 'donut doughnut sweet dessert bakery dough'},
    {'char': '🧁', 'name': 'cupcake bakery sweet dessert frosting muffin'},
    {'char': '🥂', 'name': 'clinking glasses champagne toast celebration anniversary party'},
    {'char': '🥃', 'name': 'tumbler glass whiskey bourbon liquor bar alcohol drink'},
  ],
  'Extra Symbols, Activities & Gaming': [
    {'char': '⭐', 'name': 'star rating favorite achievement'},
    {'char': '🌙', 'name': 'moon night space sleep'},
    {'char': '⚡', 'name': 'lightning electricity energy power fast'},
    {'char': '☄️', 'name': 'comet space astronomy'},
    {'char': '🪐', 'name': 'planet space saturn galaxy'},
    {'char': '🌍', 'name': 'earth africa globe world'},
    {'char': '🌎', 'name': 'earth america globe world'},
    {'char': '🌏', 'name': 'earth asia globe world'},
    {'char': '🎮', 'name': 'game controller gaming console'},
    {'char': '🕹️', 'name': 'arcade joystick gaming retro'},
    {'char': '🎲', 'name': 'dice game random chance'},
    {'char': '🧩', 'name': 'puzzle piece problem solution'},
    {'char': '♟️', 'name': 'chess pawn strategy game'},
    {'char': '🏆', 'name': 'trophy winner champion achievement'},
    {'char': '🥇', 'name': 'gold medal first place winner'},
    {'char': '🥈', 'name': 'silver medal second place'},
    {'char': '🥉', 'name': 'bronze medal third place'},
    {'char': '🎯', 'name': 'target goal focus accuracy'},
    {'char': '🚩', 'name': 'flag warning marker'},
    {'char': '🏴', 'name': 'black flag symbol'},
    {'char': '🏳️', 'name': 'white flag surrender peace'},
    // Additions (No Repetitions)
    {'char': '🧩', 'name': 'jigsaw piece connecting riddle logic game'},
    {'char': '🔮', 'name': 'magic crystal fortune teller ball future witch'},
    {'char': '🧿', 'name': 'amulet protection eye ward charm greek'},
    {'char': '🀄', 'name': 'mahjong red dragon tile matching game asian'},
    {'char': '🎨', 'name': 'palette painting art creative painter canvas draw'},
    {'char': '🎭', 'name': 'performing arts masks theater drama comedy tragedy actor'},
    {'char': '🎫', 'name': 'ticket admission pass event coupon show enter'},
    {'char': '🎬', 'name': 'clapperboard movie action cinema filming production studio'},
    {'char': '🎤', 'name': 'microphone sing audio karaoke voice music performance'},
    {'char': '🎧', 'name': 'headphone audio music sound studio listening podcast'},
    {'char': '🎸', 'name': 'guitar music instrument strings rock band acoustic'},
    {'char': '🎹', 'name': 'musical keyboard piano synthesizer notes instrument keys'},
    {'char': '🎺', 'name': 'trumpet brass jazz wind music instrument horn'},
    {'char': '🎻', 'name': 'violin orchestral string music instrument bow strings'},
    {'char': '🥁', 'name': 'drum percussion beat rhythm music instrument band sticks'},
    {'char': '📱', 'name': 'mobile phone smartphone screen wireless portable device cellular'},
    {'char': '💰', 'name': 'money bag container savings riches currency dollar sack'},
    {'char': '🧲', 'name': 'magnet load pulling attractive power physical hardware north'},
  ],
  'Activities, Tech & Objects': [
    {'char': '💻', 'name': 'laptop computer coder tech developer pc screen work'},
    {'char': '🖥️', 'name': 'desktop computer monitor screen workstation'},
    {'char': '🖨️', 'name': 'printer hardware office device output text documents'},
    {'char': '🖱️', 'name': 'computer mouse hardware pointer click desktop input'},
    {'char': '🖲️', 'name': 'trackball hardware input legacy device peripherals'},
    {'char': '💽', 'name': 'computer disk minidisc storage media legacy tech'},
    {'char': '💾', 'name': 'floppy disk save button icon vintage retro magnetic storage'},
    {'char': '💿', 'name': 'optical disk cd dvd rom storage media shiny music disc'},
    {'char': '📀', 'name': 'dvd software movie digital video laserdisc multimedia'},
    {'char': '📼', 'name': 'videocassette vhs tape retro cassette recording analog player'},
    {'char': '📷', 'name': 'camera photography picture taking shot snapshot lens hardware'},
    {'char': '📸', 'name': 'camera with flash flash photography photo session picture paparazzi'},
    {'char': '📹', 'name': 'video camera recorder camcorder recording filmmaking movie'},
    {'char': '🎥', 'name': 'movie camera cinema film theater project hollywood multimedia'},
    {'char': '📽️', 'name': 'film projector screen cinema theater projection vintage media'},
    {'char': '🎞️', 'name': 'film frames negative strip cinematography movie production clip'},
    {'char': '📞', 'name': 'telephone receiver handset phone communication incoming audio call'},
    {'char': '📟', 'name': 'pager beeper old school vintage mobile telecom electronics'},
    {'char': '📠', 'name': 'fax machine old office machine document transfer legacy transmission'},
    {'char': '📺', 'name': 'television retro tv screen broadcasting set video media monitor'},
    {'char': '📻', 'name': 'radio receiver broadcasting audio tunes tune system receiver'},
    {'char': '🎙️', 'name': 'studio microphone podcast recording vocal broadcast sound stream'},
    {'char': '🎚️', 'name': 'level slider volume mixing console adjustment hardware controller fader'},
    {'char': '🎛️', 'name': 'control knobs mixer tuning adjustment parameters hardware dial equalizer'},
    {'char': '🧭', 'name': 'compass orientation navigation direction mapping explorer geography'},
    {'char': '⏱️', 'name': 'stopwatch precision timer clock sports countdown measurement chronometer'},
    {'char': '⏲️', 'name': 'timer clock kitchen alarm countdown interval setting period time'},
    {'char': '⏰', 'name': 'alarm clock waking up time morning wake urgent ringing bell'},
    {'char': '🕰️', 'name': 'mantelpiece clock vintage antique decoration timezone period mechanical'},
    {'char': '⌛', 'name': 'hourglass done complete time limit passed terminal waiting loading'},
    {'char': '⏳', 'name': 'hourglass with flowing sand dynamic running time duration execution active process'},
    {'char': '📡', 'name': 'satellite antenna dish radar communication signal transmission link array'},
    {'char': '🔋', 'name': 'battery full power electric cell charge fuel energy accumulators'},
    {'char': '🔌', 'name': 'electric plug adapter electricity power mains terminal adapter connector socket'},
    {'char': '💡', 'name': 'light bulb idea inspiration invention brilliant thinking light source glow'},
    {'char': '🔦', 'name': 'flashlight torch dark search exploring beam illumination portable'},
    {'char': '🕯️', 'name': 'candle wax light source ritual romantic antique spooky flame wick'},
    {'char': '🧯', 'name': 'fire extinguisher safety emergency device hazard suppress flame protection'},
    {'char': '🛢️', 'name': 'oil drum barrel fuel chemical petroleum commodities storage tank'},
    {'char': '💸', 'name': 'money with wings flying cash losing capital expenses inflation payment spending'},
    {'char': '💵', 'name': 'dollar banknote cash paper currency capital us notes bank greenbacks'},
    {'char': '💴', 'name': 'yen banknote cash paper currency japanese money capital international exchange'},
    {'char': '💶', 'name': 'euro banknote cash paper currency european money financial capital'},
    {'char': '💷', 'name': 'pound banknote cash paper currency british pound sterling royal money market'},
    {'char': '💰', 'name': 'money bag cash funds rich wealth gold savings capital treasure box'},
    {'char': '💳', 'name': 'credit card debit transaction payment bank plastic money purchase processing finance'},
    {'char': '💎', 'name': 'gem stone diamond crystal jewel precious rich wealth hard structure luxury'},
    {'char': '⚖️', 'name': 'balance scale scales of justice court fair legal equilibrium weight judgment'},
    {'char': '🧰', 'name': 'toolbox chest maintenance repairs storage kit hardware engineering container'},
    {'char': '🔧', 'name': 'wrench spanner configuration tool maintenance repair fix construction hardware'},
    {'char': '🔨', 'name': 'hammer hitting striking tool build construction metalwork workshop hardware'},
    {'char': '⚒️', 'name': 'hammer and pick mining tools extraction digging manual labor work safety'},
    {'char': '🛠️', 'name': 'hammer and wrench tools customization servicing maintenance setups technical workshop'},
    {'char': '⛏️', 'name': 'pickaxe mining pick digging heavy excavation mineral production tools'},
    {'char': '🔩', 'name': 'nut and bolt fasteners mechanics hardware components connection industrial engineering'},
    {'char': '⚙️', 'name': 'gear cog machine parameters options engineering settings setup processing mechanics core'},
    {'char': '🧱', 'name': 'brick wall solid structural foundation masonry bricklaying construction barrier'},
    {'char': '⛓️', 'name': 'chains link metal constraints locked cryptography secure anchor bound processing loop'},
    {'char': '🧲', 'name': 'magnet magnetic field pull attraction physical mechanics hardware physics link force'},
    {'char': '🔫', 'name': 'pistol handgun firearm water gun weapon shooting defense armaments trigger'},
    {'char': '💣', 'name': 'bomb explosion dangerous item explosive blast destructive countdown crash volatile'},
    {'char': '🧨', 'name': 'firecracker explosive dynamic fireworks popping spark celebration custom blast'},
    {'char': '🪓', 'name': 'axe chopping tool splitting lumberjack woodcutter hardware weapon steel'},
    {'char': '🔪', 'name': 'kitchen knife blade chef slicing sharp edge cutlery tool weapon stab'},
    {'char': '🗡️', 'name': 'dagger short sword weapon blade tactical sharp medieval combat hardware'},
    {'char': '⚔️', 'name': 'crossed swords combat fight duel warfare clash confrontation rival arms'},
    {'char': '🛡️', 'name': 'shield protection defense guard security armor block firewalls safety package'},
    {'char': '🚬', 'name': 'smoking cigarette nicotine addiction smoke break puff toxic tabacco'},
    {'char': '⚰️', 'name': 'coffin box burial funeral dead death cemetery spooky grave wood structural'},
    {'char': '⚱️', 'name': 'funeral urn ashes vessel mourning memorial container ceramic antique dead'},
    {'char': '🏺', 'name': 'amphora ancient vase ceramic greek pottery container storage vessel fluid liquid'},
    {'char': '🔮', 'name': 'crystal ball prediction fortune future see mystical magic sorcery fortune-teller'},
    {'char': '🧿', 'name': 'nazar amulet evil eye protection charm blue bead talisman mystic shielding'},
    {'char': '📿', 'name': 'prayer beads rosary ritual meditation spiritual count beads chanting mantra faith'},
    {'char': '💈', 'name': 'barber pole haircut styling vintage symbol spiral stripes processing salon hairdressing'},
    {'char': '🧪', 'name': 'test tube chemistry lab experiment scientific analysis fluids development research rx biological'},
    {'char': '🧫', 'name': 'petri dish biology laboratory cell culture growth experiment bacterial colony parsing tracking'},
    {'char': '🧬', 'name': 'dna strand helix genetic engineering biology life micro components structure parsing sequence analytics'},
    {'char': '🔬', 'name': 'microscope science laboratory investigation structural details zoom exploration magnifying scientific data'},
    {'char': '🔭', 'name': 'telescope space observation astronomy stars tracking distant galaxy optical magnifier'},
    {'char': '💉', 'name': 'syringe medical injection vaccine blood sample needle treatment clinical laboratory safety pharmacy'},
    {'char': '🩸', 'name': 'drop of blood donation medical clinical hematology analysis life fluid red wound bleeding'},
    {'char': '💊', 'name': 'pill capsule tablet medication pharmacy prescription medical dose tablet treatment pharmacy drugs'},
    {'char': '🩹', 'name': 'adhesive bandage bandaid injury recovery plaster skin protection care treatment dressing application'},
    {'char': '🩺', 'name': 'stethoscope clinical checkup doctor medical heart rate listen breathing medicine health gear'},
    {'char': '🚪', 'name': 'door entrance exit pathway portal access open closing gateway room security entry'},
    {'char': '🪞', 'name': 'mirror looking glass reflection self vanity glass structural decor frames matching'},
    {'char': '🧳', 'name': 'luggage baggage travel suitcase trip holiday layout packaging transit item'},
    {'char': '☕', 'name': 'coffee cup tea hot drink break workspace stimulant fuel morning cafe mug'},
    {'char': '🎉', 'name': 'party popper explosion confetti celebration event anniversary milestone dynamic sparks'},
    {'char': '🚀', 'name': 'rocket space transport ship launch blast off speed fast processing dynamic mission'},
    // Additions (No Repetitions)
    {'char': '🛹', 'name': 'skateboard action sports recreation skating roll board'},
    {'char': '🚲', 'name': 'bicycle transport eco friendly cycle exercise wheels pedal'},
    {'char': '🛵', 'name': 'scooter vespa motor delivery transit driver wheels moped'},
    {'char': '🚗', 'name': 'automobile car transport travel driver vehicle commute'},
    {'char': '✈️', 'name': 'airplane flight travel transport sky destination tourism aviation'},
    {'char': '🚁', 'name': 'helicopter air travel chopper transport tactical aviation rotor'},
    {'char': '🛰️', 'name': 'satellite orbital tracking space hardware comms tech array instruments'},
    {'char': '🛸', 'name': 'ufo flying saucer alien mystery space extra terrestrial craft'},
  ],
  'Country Flags': [
    {'char': '🚩', 'name': 'triangular flag on post warning marker'},
    {'char': '🏴', 'name': 'black flag symbol'},
    {'char': '🏳️', 'name': 'white flag surrender peace'},
    {'char': '🇧🇼', 'name': 'botswana flag national country'},
    {'char': '🇿🇼', 'name': 'zimbabwe flag national country'},
    {'char': '🏳️‍🌈', 'name': 'rainbow flag pride lgbtq colors'},
    {'char': '🇺🇸', 'name': 'united states america flag us usa national country'},
    {'char': '🇬🇧', 'name': 'united kingdom flag uk britain national country royal union jack'},
    {'char': '🇨🇦', 'name': 'canada flag maple leaf canadian national country'},
    {'char': '🇯🇵', 'name': 'japan flag japanese nippon sun national country'},
    {'char': '🇩🇪', 'name': 'germany flag german deutschland national country'},
    {'char': '🇫🇷', 'name': 'france flag french tricolor national country'},
    {'char': '🇮🇹', 'name': 'italy flag italian national country'},
    {'char': '🇪🇸', 'name': 'spain flag spanish national country'},
    {'char': '🇧🇷', 'name': 'brazil flag brazilian south america national country'},
    {'char': '🇦🇺', 'name': 'australia flag australian down under national country'},
    {'char': '🇮🇳', 'name': 'india flag indian national country hindi tricolor'},
    {'char': '🇨🇳', 'name': 'china flag chinese red star national country'},
    {'char': '🇲🇽', 'name': 'mexico flag mexican south america national country'},
    {'char': '🇿🇦', 'name': 'south africa flag african national country rainbow nation'},
    {'char': '🇰🇷', 'name': 'south korea flag korean national country seoul'},
    {'char': '🇳🇱', 'name': 'netherlands flag dutch Holland national country'},
    {'char': '🇨🇭', 'name': 'switzerland flag swiss cross red national country'},
    {'char': '🇷🇺', 'name': 'russia flag russian federation national country'},
    {'char': '🇸🇪', 'name': 'sweden flag swedish scandinavian cross national country'},
    {'char': '🇳🇴', 'name': 'norway flag norwegian scandinavian cross national country'},
    {'char': '🇩🇰', 'name': 'denmark flag danish scandinavian cross national country'},
    {'char': '🇫🇮', 'name': 'finland flag finnish national country'},
    {'char': '🇮🇪', 'name': 'ireland flag irish tricolor national country republic'},
    {'char': '🇳🇿', 'name': 'new zealand flag nz national country'},
    {'char': '🇸🇬', 'name': 'singapore flag national country asian'},
    {'char': '🇲🇾', 'name': 'malaysia flag national country asian'},
    {'char': '🇹🇭', 'name': 'thailand flag thai national country asian'},
    {'char': '🇻🇳', 'name': 'vietnam flag vietnamese national country asian'},
    {'char': '🇵🇭', 'name': 'philippines flag filipino national country asian'},
    {'char': '🇮🇩', 'name': 'indonesia flag national country asian'},
    {'char': '🇸🇦', 'name': 'saudi arabia flag arabic green national country'},
    {'char': '🇦🇪', 'name': 'united arab emirates flag uae dubai arab national country'},
    {'char': '🇮🇱', 'name': 'israel flag jewish star david national country'},
    {'char': '🇹🇷', 'name': 'turkey flag turkish crescent star national country'},
    {'char': '🇪🇬', 'name': 'egypt flag egyptian national country african'},
    {'char': '🇳🇬', 'name': 'nigeria flag nigerian national country african'},
    {'char': '🇰🇪', 'name': 'kenya flag kenyan national country african shield'},
    {'char': '🇦🇷', 'name': 'argentina flag argentine south america national country sun'},
    {'char': '🇨🇱', 'name': 'chile flag chilean south america national country'},
    {'char': '🇨🇴', 'name': 'colombia flag colombian south america national country'},
    {'char': '🇺🇦', 'name': 'ukraine flag ukrainian blue yellow national country'},
    {'char': '🇵🇱', 'name': 'poland flag polish national country'},
    {'char': '🇬🇷', 'name': 'greece flag greek national country stripes'},
    {'char': '🇵🇹', 'name': 'portugal flag portuguese national country'},
    {'char': '🇧🇪', 'name': 'belgium flag belgian national country'},
    {'char': '🇦🇹', 'name': 'austria flag austrian national country'},
    {'char': '🇳🇵', 'name': 'nepal flag nepalese non rectangular country shape'},
    {'char': '🇵🇰', 'name': 'pakistan flag pakistani crescent national country'},
    {'char': '🇪🇺', 'name': 'european union flag eu europe unity stars symbol international'},
    {'char': '🇺🇳', 'name': 'united nations flag un global world map diplomacy symbol'},
  ]
};